//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Customer = new HashSet<Customer>();
        }
    
        public int RoomID { get; set; }
        public string RoomType { get; set; }
    
        public virtual ICollection<Customer> Customer { get; set; }
    }
}
